# Top Indian Stocks for Search Autocomplete
STOCKS = [
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries Ltd"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services Ltd"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank Ltd"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank Ltd"},
    {"symbol": "INFY.NS", "name": "Infosys Ltd"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever Ltd"},
    {"symbol": "ITC.NS", "name": "ITC Ltd"},
    {"symbol": "SBIN.NS", "name": "State Bank of India"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel Ltd"},
    {"symbol": "LICI.NS", "name": "Life Insurance Corporation of India"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank Ltd"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro Ltd"},
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies Ltd"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank Ltd"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints Ltd"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki India Ltd"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical Industries Ltd"},
    {"symbol": "TITAN.NS", "name": "Titan Company Ltd"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance Ltd"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement Ltd"},
    {"symbol": "ONGC.NS", "name": "Oil & Natural Gas Corporation Ltd"},
    {"symbol": "NTPC.NS", "name": "NTPC Ltd"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors Ltd"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corporation of India Ltd"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel Ltd"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises Ltd"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports and Special Economic Zone Ltd"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra Ltd"},
    {"symbol": "WIPRO.NS", "name": "Wipro Ltd"},
    {"symbol": "COALINDIA.NS", "name": "Coal India Ltd"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv Ltd"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum Corporation Ltd"},
    {"symbol": "NESTLEIND.NS", "name": "Nestle India Ltd"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra Ltd"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries Ltd"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries Ltd"},
    {"symbol": "CIPLA.NS", "name": "Cipla Ltd"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries Ltd"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories Ltd"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank Ltd"},
    {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories Ltd"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors Ltd"},
    {"symbol": "SBILIFE.NS", "name": "SBI Life Insurance Company Ltd"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals Enterprise Ltd"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products Ltd"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto Ltd"},
    {"symbol": "UPL.NS", "name": "UPL Ltd"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp Ltd"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel Ltd"},
    {"symbol": "ZOMATO.NS", "name": "Zomato Ltd"},
    {"symbol": "PAYTM.NS", "name": "One 97 Communications Ltd (Paytm)"},
    {"symbol": "NYKAA.NS", "name": "FSN E-Commerce Ventures Ltd (Nykaa)"},
    {"symbol": "POLICYBZR.NS", "name": "PB Fintech Ltd (PolicyBazaar)"},
    {"symbol": "SWIGGY.NS", "name": "Swiggy Ltd"}
]
